import { v4 as uuidv4 } from "uuid";

let adsData = [
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/sheypoor-logo.png",
		favorite: true,
		group: "Classic car",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: true,
		group: "Doe",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: true,
		group: "Doe",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: true,
		group: "Doe",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: true,
		group: "Doe",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: true,
		group: "Doe",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: true,
		group: "Doe",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "Doe",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "Doe",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: [
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
			"/images/home.webp",
		],
		imgLogo: "/images/shypoor-logo.png",
		favorite: false,
		group: "John",
		title: "500 m building sea view furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
];

export default adsData;
