import { v4 as uuidv4 } from "uuid";

let adsData = [
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
	{
		id: uuidv4(),
		imgAds: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "Django expert project oriented course",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
];

export default adsData;
