import { v4 as uuidv4 } from "uuid";

let adsData = [
	{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/sheypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
{
		id: uuidv4(),
		imgAds: "/images/home.webp",
		imgLogo: "/images/shypoor-logo.png",
		like: false,
		numberOfPhotos: 6,
		title: "500 m sanded building/sea view/furnished",
		price: 323_000,
		city: "Tehran",
		time: "moments ago",
	},
];

export default adsData;
