let headerData = [
	{
		id: 1,
		name: "Personal stuff",
		iconName: "Shirt",
		allGroup: "All groups of personal stuff",
		title: [
			"Clothes, bags and shoes",
			"Jewelry and watches",
			"Hygiene, cosmetics and medicine",
			"Clothes, baby and baby accessories",
			"Other personal items",
		],
	},
	{
		id: 2,
		name: "Phones and tablets",
		iconName: "TabletSmartphone",
		allGroup: "All groups of Phones and tablets",
		title: [
			"Mobile and tablet",
			"Mobile accessories",
			"SIM card and landline",
		],
	},
	{
		id: 3,
		name: "Office and commercial",
		iconName: "Computer",
		allGroup: "All groups of Office and commercial",
		title: [
			"Industrial machinery and equipment",
			"Tools and accessories",
			"Office Supplies",
			"Medical and laboratory equipment",
			"Other",
		],
	},
	{
		id: 4,
		name: "Electronic appliances",
		iconName: "Monitor",
		allGroup: "All groups of Electronic appliances",
		title: [
			"Laptop and computer",
			"Video and Audio",
			"Camera, video and accessories",
			"Game consoles and accessories",
		],
	},
	{
		id: 5,
		name: "Sports and leisure",
		iconName: "Umbrella",
		allGroup: "All groups of Sports and leisure",
		title: ["Bicycle", "Travel Tour", "Sports", "Books and stationery"],
	},
	{
		id: 6,
		name: "Home Appliances",
		iconName: "Armchair",
		allGroup: "All groups of Home Appliances",
		title: [
			"Furniture and wooden accessories",
			"Electrical and kitchen appliances",
			"Kitchen utensils and appliances",
			"Interior decoration and lighting",
		],
	},
	{
		id: 7,
		name: "Services and business",
		iconName: "Briefcase",
		allGroup: "All groups of Services and business",
		title: ["John", "Doe", "Alice", "Bob"],
	},
	{
		id: 8,
		name: "Advertising and recruiting",
		iconName: "KanbanSquare",
		allGroup: "All groups of Advertising and recruiting",
		title: [
			"Hairdressing and beauty",
			"Education",
			"Equipment rental",
			"Moving and transportation",
		],
	},
	{
		id: 9,
		name: "Property and land",
		iconName: "Home",
		allGroup: "All groups of Property and land",
		title: [
			"Buy and sell villas",
			"Mortgage and rent of houses and apartments",
			"Buying and selling houses and apartments",
			"Short term villa and suite rental",
		],
	},
	{
		id: 10,
		name: "Car and motorcycle",
		iconName: "CarFront",
		allGroup: "All groups of Car and motorcycle",
		title: ["Car", "Car auction", "Motorcycle", "Classic car"],
	},
];

export default headerData;
