import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/fixed/Navbar";
import Footer from "@/components/fixed/Footer";

import { NextAuthProvider } from "./providers";
import { DataProvider } from "@/context/data.context";

import UserList from "@/components/UserList";
// import UserDetail from "@/components/UserDetail";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} mx-20`}>
				<NextAuthProvider>
					<DataProvider>
						<Navbar />
						{children}
						<Footer />
						<UserList />
						{/* <UserDetail /> */}
					</DataProvider>
				</NextAuthProvider>
			</body>
		</html>
	);
}
